"""CLI entrypoint for the IaC agent."""

import sys
from pathlib import Path

import click

from .crew import create_crew
from .io import (
    ensure_output_dir,
    read_requirements_file,
    read_requirements_string,
    write_proposal,
)
from .prompts import DRAFT_TEMPLATE
from .validator import validate_proposal


@click.command()
@click.option(
    "--requirements-file",
    "-f",
    type=click.Path(exists=True),
    help="Path to requirements markdown file",
)
@click.option(
    "--requirements",
    "-r",
    help="Requirements as string (supports multi-line)",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="Generate draft proposal without LLM (no API key required)",
)
@click.option(
    "--skip-validation",
    is_flag=True,
    help="Skip format validation (not recommended)",
)
def main(requirements_file: str, requirements: str, dry_run: bool, skip_validation: bool):
    """
    CrewAI-based IaC agent MVP for AWS Terraform baseline proposals.
    
    Accepts AWS requirements and produces a minimal Terraform baseline proposal.
    """
    # Read requirements
    if requirements_file:
        req_text = read_requirements_file(requirements_file)
    elif requirements:
        req_text = read_requirements_string(requirements)
    else:
        click.echo("Error: Must provide either --requirements-file or --requirements", err=True)
        sys.exit(1)
    
    if not req_text.strip():
        click.echo("Error: Requirements cannot be empty", err=True)
        sys.exit(1)
    
    # Generate proposal
    if dry_run:
        click.echo("Running in dry-run mode (no LLM, using template)...")
        proposal = DRAFT_TEMPLATE.replace(
            "[Architecture details would be generated by LLM based on requirements]",
            f"Requirements provided:\n{req_text}"
        )
    else:
        click.echo("Creating CrewAI crew...")
        crew = create_crew(req_text, dry_run=False)
        
        click.echo("Running crew to generate proposal...")
        try:
            result = crew.kickoff()
            proposal = str(result)
        except Exception as e:
            click.echo(f"Error during crew execution: {e}", err=True)
            click.echo("Falling back to draft template...", err=True)
            proposal = DRAFT_TEMPLATE.replace(
                "[Architecture details would be generated by LLM based on requirements]",
                f"Requirements provided:\n{req_text}\n\nError: {e}"
            )
    
    # Validate proposal
    if not skip_validation:
        click.echo("Validating proposal format...")
        is_valid, errors = validate_proposal(proposal)
        if not is_valid:
            click.echo("Validation errors found:", err=True)
            for error in errors:
                click.echo(f"  - {error}", err=True)
            if not dry_run:
                click.echo("\nProposal may not meet format requirements.", err=True)
                click.echo("Consider reviewing the output manually.", err=True)
    
    # Write output
    output_dir = ensure_output_dir()
    write_proposal(output_dir, proposal)
    
    # Print to stdout
    click.echo("\n" + "=" * 80)
    click.echo("PROPOSAL OUTPUT")
    click.echo("=" * 80 + "\n")
    print(proposal)
    click.echo("\n" + "=" * 80)
    click.echo(f"Proposal also written to: {output_dir / 'proposal.md'}")
    click.echo("=" * 80)


if __name__ == "__main__":
    main()

